### ISSUE TITLE
Serverless can?

### ISSUE THREAD

**Issue by kaihendry** [mikestefanello/pagoda#20]
Can this project be deployed as a lambda function like so https://github.com/kaihendry/ltabus/blob/master/template.yml ?

Or does it require to be long running?

**Comment by mikestefanello** [comment]
While I haven't used this with Lambda before, I cannot think of a reason why it wouldn't work fine. There is nothing required to be long running. I would think something like GCP's Cloud Run would be the easier and better option for serverless, but that's possibly because I'm just familiar with that product. If you give it a try, please let me know how it goes and perhaps there's some resources that can be included in this project to make any serverless deployment easier.

**Comment by gedw99** [comment]
Fly is automatically serverless. It will scale to zero after 5 minutes.
It can also auto scale up in multiple regions.

Fly can also scale out the db too.
