### ISSUE TITLE
Rendering data returned by ent query

### ISSUE THREAD

**Issue by Jimmy99** [mikestefanello/pagoda#31]
Hi mikestefanello
Do you have some pointers about how to render the data returned by an ent orm query? For example do you create a struct for the data returned and range through the data returned by the query to populate the struct or what is your suggested approach or how you have used it in the past? I am just not so clear on how you feed the query data into Page.Data

**Comment by mikestefanello** [comment]
Hi @Jimmy99 

Good question. It's really up to you and what your page requires. `Page.Data` can (obviously) be anything. In my experience, it usually makes sense to have a custom type for the given page that contains everything you want to provide to the templates. You populate that then assign that to `Page.Data`. It's very flexible.

IE (very made up, simple example):

```
type shoppingCartPageData struct {
	Products []ent.Product
	PromoCode ent.PromoCode
	Total float64
}

func (c *shoppingCart) Get(ctx echo.Context) error {
	page := controller.NewPage(ctx)
	page.Layout = "cart"
	page.Name = "Shopping cart"
	
        // Fetch data from ent, etc....
	page.Data = shoppingCartPageData{
		Products: products,
		PromoCode: promo,
		Total: productsSumPrice(products),
        }

	return c.RenderPage(ctx, page)
}
```

And in your template:

```
{{- range .Data.Products}}
	<div class="product">{{.Name}} (${{.Price}})</div>
{{- end}}

Total: ${{.Data.Total}}
```

Unless your page really will only ever require 1 thing, then you can just assign that directly to `Page.Data` rather than having a _wrapper_ type to contain everything.

There's a very basic example of passing an `ent` entity (user) to the template, though it's not part of `Page.Data`:

- https://github.com/mikestefanello/pagoda/blob/main/pkg/controller/page.go#L72
- https://github.com/mikestefanello/pagoda/blob/main/templates/pages/home.gohtml#L18

Let me know if that helps and if you run in to any problems.
