### ISSUE TITLE
sqlc instead of ent

### ISSUE THREAD

**Issue by omid9h** [mikestefanello/pagoda#34]
I would like to know your opinion on using [sqlc](https://github.com/kyleconroy/sqlc) instead of Ent as the database layer. Do you think there is a good way to add it as an optional or interchangeable option alongside Ent, or should we consider creating a separate fork for it

**Comment by mikestefanello** [comment]
I think a separate fork would be best. The main principle of this project is that it's a starter kit and everything should be somewhat easy to swap in and out. If anything were to be introduced or changed within this project, I would want to focus on making the swaps easy, rather than providing out of the box integration with various other things (like sqlc). I wanted to make everything in the container more of a generic interface to make swapping easier, but I assume whoever uses this project will make so many changes that none of those interfaces would provide much value and would be removed at some point.

There's also endless options for everything, so it would be difficult to maintain if we included everything that anyone wanted. It's also hard to then decide what gets included and what doesn't.

If you do work on a fork with sqlc, please do share it here. And if you come across anything in this project that can be improved to make swapping easier, please let me know.

Thanks
