### ISSUE TITLE
A few suggestions / questions from a first time user

### ISSUE THREAD

**Issue by saurori** [mikestefanello/pagoda#53]
Firstly I'd like to say thanks for putting together this "framework" - it's a great alternative to something like Buffalo or Bud. I plan on experimenting with it and adapting to my own base default template, trying a different template engine `templ` and adding an assets pipeline for js/css.

Here are a few observations / questions I noticed from using the template for the first time (some of which could become a PR based on feedback):

1. Pages are cached, but is it intended for Routes to be cached as well? For example, if you start the application and visit `/about`, change the `/about` route to `/about-us` (and rerun), then visit `/about`, the page renders. I would expect a change in the router would no longer route to any page, cached or not.
2. [config.GetConfig()](https://github.com/mikestefanello/pagoda/blob/v0.10.0/config/config.go#L133-L136) appears to be guessing where the config directory is based on what sub-package file is loading the config. I think a better approach would be something like:
```go
	// Get the basepath / project root
	_, b, _, _ := runtime.Caller(0)
	basepath := filepath.Dir(b)
	...
	viper.AddConfigPath(basepath)
```
3. A `make down` command would be useful, e.g.: `$(DCO_BIN) down`

**Comment by mikestefanello** [comment]
You're welcome. I'm glad to hear that you're finding it useful. Keep me posted on your experience with `templ`. I've been looking at it recently and it looks very promising. I'm waiting for the Goland plugin to be done so I can really dive in. While the std lib templates are quite powerful and flexible, they do leave a lot to be desired, and it was not easy to provide the solution that I did; and I'm not too thrilled with how some of the function and nested templates calls came out.

1. I'm a little confused with the example that you outlined. Those would be separate routes so one should not affect the other. Can you elaborate a little further? By default, nothing will be cached. If you set your Page's `Cache.Enabled` to `true`, the output will be cached. The cache middleware will currently only serve from the cache if it's a `GET` request and the user is not logged in. You can, of course, alter that behavior to fit your needs though. As I'm writing this I think I realize what you meant -  by _change_ do you mean in the browser or the route definition? I guess you mean the latter (I assumed the former at first). Did we restart the application after making that change? I haven't tested this but I assume you would get a 404 if there is no `/about` route registered any more. I don't think the middleware would even get executed.
2. Yes, that would work. I used the same trick to get the `templates` directory. I was hoping by now there would be a better/standardized way of doing that, but it looks like there's not. I used the solution I have now because it's not too uncommon that your build process includes the config at the root when building an image, for example. So with the multiple paths, it allows there to be some flexibility and preference.
3. I agree. I can add that in quickly.

**Comment by saurori** [comment]
Regarding Number 2:

Steps to reproduce:
1. run `make up`
2. run `make run`
3. In a browser, visit `localhost:8000/about`
4. Kill the app
5. Change [this line](https://github.com/mikestefanello/pagoda/blob/v0.10.0/pkg/routes/router.go#L75) in the router to `g.GET("/about-us", about.Get).Name = "about-us"`
6. run `make run`
7. In a browser, visit `localhost:8000/about`

I would expect a `404`, but the page renders `200`

**Comment by mikestefanello** [comment]
I would expect that too. Thanks for the detailed steps. I am able to reproduce. I'll have to look in to it. I don't understand why the middleware is being executed if there's no match for the route.

**Comment by mikestefanello** [comment]
Looks like it has to do with how the `Group()` is being used:

- https://github.com/labstack/echo/issues/1981
- https://github.com/labstack/echo/pull/2411

**Comment by mikestefanello** [comment]
Thinking about this some more, the middleware should definitely be executing even if there's no match found. I don't see anyway for the cache middleware to know that it's a 404 at that point. I don't think Echo exposes that in any way, unfortunately. I think you'll just have to clear the cache if you're making a change like this. I added a `cache-clear` command to the Makefile to make this easier. I also included `stop` and `down`.

**Comment by saurori** [comment]
Well that's unfortunate. It might be useful to put a warning about that in the README. Thanks for looking into that and adding those additional commands.

**Comment by saurori** [comment]
@mikestefanello I made an initial pass at trying `templ` and converting the codebase to use it. Check it out [at this branch](https://github.com/saurori/pagoda/tree/templ) if you're interested. My initial impressions of `templ` are mostly positive, but there were some gotchas:

1. I was expecting to use "plain Go" in the template functions but that's not exactly how it works. For example, you can't build variables inside a templ function such as `allNames := append(names, "John")`, so you need to sometimes approach writing the template differently, or call plain Go functions from the templ function.
2. There is a question of which strategy to use for passing data into the template (see [prop drilling](https://templ.guide/syntax-and-usage/context/#prop-drilling)). I opted for "Coupling" and passing in the `Page` struct
3. It's an advantage to have everything type safe in the template but that means operating on data passed as `any` requires casting in the templ function such as `if form, ok := page.Form.(*types.LoginForm); ok {`.

I think I would need to build a real app to see if there are any sharp edges with this implementation.

**Comment by mikestefanello** [comment]
It looks like you made some really great progress. I like the approach that you took. My initial thought when I saw templ and considered using it with this project was dealing with potential import cycle problems between the templates package and either the controller or routes package, but it looks like you avoided that nicely (though as you pointed out in the 3rd point, maybe this will become an issue). I also think the coupling approach is superior to context for the templates. And your last point about using this in a real app was another concern of mine.. it may seem nice in a simple example but a real problem in a more complex one.

**Comment by saurori** [comment]
Funny you mention it, I did hit an import cycle problem but found a way around it. It was an issue in controller tests but I changed those tests to use `package controller_test` to avoid. 

I think the coupling approach is the way to go. For number 3, you could get around type casting by passing additional structs to a template such as `page.Component = pages.Contact(&page, &contactForm)` and not set the `page.Form`. I was trying to stick to the original design choices and change less, but looking at it now I think setting less `any` types on Page is a better approach.

**Comment by leomorpho** [comment]
Thanks for your awesome work @mikestefanello, this is truly a fantastic starter for anyone wanting to use Go/HTMX. @saurori thanks for your work on templ integration too. I used your branch to start a few projects now and I must say I love the Pagoda setup even more now, templ truly makes the dev experience fantastic compared to the default html package. Not sure if it's useful, but my branch lives [here](https://github.com/leomorpho/pagoda/tree/pragmatic). I meant to keep it clean but it's got a lot of extra changes I use by default in my projects...perhaps it will be useful.

**Comment by mikestefanello** [comment]
@leomorpho Thank you! I'm very glad this project turned out to be useful for you. Please feel free to share any feedback about this and templ. Maybe at some point I'll bring templ in. I haven't yet given it a real try yet but I plan to.

**Comment by leomorpho** [comment]
For anyone interested, I have a heavily modified fork that uses Templ instead of gotemplates. I personally haven't looked back. I trust my code so much more than back when I had to pass maps to components. I love the static typing, and it's got some quite fantastic template composition syntax. It's OSS: https://github.com/leomorpho/GoShip
I'd be happy to merge some things back into Pagoda, but it's just gotten quite off-road from the initial pagoda fork...
