### ISSUE TITLE
Request for Tailwind CSS Support

### ISSUE THREAD

**Issue by jbowa** [mikestefanello/pagoda#55]
Hi thank you for building/maintaining this project. Quick question, Have we considered replacing the way we are currently styling the project with the popular Tailwind utility library? We could perhaps include this in the makefile as a build step for production or run a script for development.

**Comment by mikestefanello** [comment]
Hi. You're very welcome.

I considered it in the beginning when I was evaluating all options for CSS. There's so many good options that it's impossible to make everyone happy with something out of the box. Replacing Bulma is extremely easy - it's just a single `link` element that you can change [here](https://github.com/mikestefanello/pagoda/blob/main/templates/components/core.gohtml#L16). Other than that it's just classes which are part of the templates that I assume you'd be removing for your own project anyway.

I chose Bulma because I wanted something as simple and productive as possible. I didn't want any additional build steps, etc. And I wanted plenty of pre-built elements/components/etc that only require a single class to style (as opposed to what Tailwind offers; last I checked). I originally was going to use Bootstrap, since I've used it a lot, but I wanted something that had no JS dependencies to keep things as simple and light as possible. My philosophy with this project and in choosing HTMX/Alpine/Bulma was that I wanted to be able to produce a decent frontend without having to get deep into complex frontend development and endless frameworks, tools, etc (I'd rather focus on the backend).

**Comment by jbowa** [comment]
Makes sense. Thanks Mike.

**Comment by jbowa** [comment]
For anyone who comes across this found [@unocss ](https://unocss.dev/) to be a great replacement. Zero runtime + allows me to use tailwind via presents…
