### ISSUE TITLE
example repo ?

### ISSUE THREAD

**Issue by gedw99** [mikestefanello/pagoda#7]
The structure and patterns are pretty nice, and really help with not reinventing the wheel again.

I was wondering if you have or are planning or wanting example repos that use this template.

Also i assume that this template approach allows golang developers to work in their real repo, and when the architecture of the template repo changes, they can do a git merge into their example repo ? 

Anyways nice code

**Comment by mikestefanello** [comment]
Thank you for the kind words. I'm glad to hear you like it and find it useful.

I'm not planning example repos. I thought this repo was exactly that since the idea is that you'd use this as a starting point for your project - completely free to add/remove/change everything included to fit your exact needs. It already includes a very basic example web app. Were there any specific things you would be interested to see implemented, especially as examples? I could always include more in this template.

I thought the idea of a template rather than a framework would make more sense so you're not locked in to any patterns, systems, dependencies, etc. I didn't think anyone starting with this template would ever have a reason to merge in updates from it since I suspect most will diverge quickly and dramatically.

**Comment by gedw99** [comment]
Your right. Its a basis as your say.  I really like it so far.. KISS.

I will make a few issues about things that I feel are missing...

**Comment by mikestefanello** [comment]
> Your right. Its a basis as your say. I really like it so far.. KISS.

Thanks again!

> I will make a few issues about things that I feel are missing...

Sounds good.
