### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by mac4u** [mikestefanello/pagoda#71]
Hi,

I am setting up a new project and I am getting an error
Go, docker, docker-composed installed.
OS Windows 11 Pro + WSL.

When running "make up" I am getting with error:

'{' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
up -d
process_begin: CreateProcess(NULL, up -d, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:48: up] Error 2

![image](https://github.com/mikestefanello/pagoda/assets/16140447/33c8f8d5-db3a-4462-aa04-67a5e9e87e51)

**Comment by mikestefanello** [comment]
Sorry you're having this problem. The makefile attempt to determine which command you have installed for docker compose is a bit hacky. Depending on the version, some have `docker-compose` and some have `docker compose`. I also only use Linux, so my solution may not work so nicely on other systems.

`make up` really just runs `docker-compose up -d` (or `docker compose` if that's how it is on your system). So, you can just run that yourself. Let me know if that works.

Worth noting that I'm in the middle of updating this project to default to using SQLite rather than Postgres and Redis so docker will soon no longer be needed at all (https://github.com/mikestefanello/pagoda/issues/69).

**Comment by mac4u** [comment]
Hi,
Thank you for your answer. It`s right on the money. 
Running the same command from WSL works. 
Running it from Windows command lines fails.
