### ISSUE TITLE
API endpoint example.

### ISSUE THREAD

**Issue by GeraltO18** [mikestefanello/pagoda#79]
Hi @mikestefanello,
Wouldn't it be nice to have an example about make simple API endpoints?. We do have the handlers where we can serve the html page, but it would be nice to define just an API where we can return JSON instead of Html page. When I attempted to do this, I wasn't able to do this due to the CSRF token. I am not sure if there is any obvious way, if so, please excuse my ignorance.

Here is my scenario, I was using the html pages for a while but now I am developing a specific frontend. which will make API call to the server. So, what I tried is to make a new pkg called API and defined the endpoints however, only the GET request where get responded while post fail with bad request. please let me know your thoughts on this.

Thank you so much for taking time.

**Comment by mikestefanello** [comment]
Hi,

I didn't want to provide examples for API endpoints because the main purpose of this starter kit is to build server-side rendered web apps rather than APIs. If I was intending to support or focus on APIs, I would have taken very different approaches. Focusing on just one allows me to make decisions that are best for that whereas needing to support both can make it quite difficult.

It is still very easy to add JSON endpoints. Rather than providing output via the template renderer, you can use Echo's `JSON()` method on the `echo.Context` to render your JSON - and that's it. The CSRF middleware is, by default, applied to the entire router (see `BuildRouter()`). You can remove that and optionally only use it on routes that provide HTML forms, for example.

If you have any more questions, please feel free to re-open this.

Thanks

**Comment by GeraltO18** [comment]
Hi @mikestefanello, 
Thanks for your reply! I completely agree with your perspective. When you mentioned, "I would have taken very different approaches," I'm curious to know more. What different approaches would you take? I'm asking because I'm really impressed with this project.

Currently, I'm attempting to develop a similar module that I can import into Pagoda, like a plugin. If I'm successful in completing it, would it be possible to add the module to Pagoda so that it's only available when the package is imported? I'd love to hear your thoughts on this.

Thanks.

**Comment by mikestefanello** [comment]
Great question and thank you for the kind words. I'm always happy to hear that others are finding this project useful.

It's hard to remember because this project started about three years ago, and much of the research and design decisions were done back then. At some point I did have an idea to start another similar project that was meant specifically for APIs but I never ended up doing it. I think a project this this is way better suited for a complete starter kit than if you were developing an API. I don't think many people would want something similar for an API, but I could be wrong. There's just so many things you need (in my opinion) when you're building a SSR web app like this, that having everything put together for you as a starting point seems way more valuable than if you were just producing an API.

As for what I would have done differently, like I said, it's hard to remember, but I would certainly put more thought to which router I used, how to generate API docs automatically, perhaps better type-safety when dealing with HTTP requests, authentication method, error handling and validation for responses, some uniform structure to fetching entities and the responses (ie, paging, filtering, sorting, etc, etc).

What sort of module are you planning to develop? Would it be to facilitate some sort of an API? This being a starter kit means that anyone can easily use it and import whatever they want to (and most importantly, remove whatever they want to). So unless it really serves a purpose that you need in a SSR web app, I wouldn't consider having it be included by default.

**Comment by GeraltO18** [comment]
> There's just so many things you need (in my opinion) when you're building a SSR web app like this, that having everything put together for you as a starting point seems way more valuable than if you were just producing an API.

I totally agree with you. Which is why I think would be better if it is a part of pagoda itself. 

Problem: For smaller projects, it is easier with SSR but when the project needs some complicated interactions with the user. I had to go away from pagoda :(

As for the module idea, I think Pagoda is perfect for small businesses or side projects, but once you start scaling up, you’ll need API endpoints that can work with the frontend. That’s why I’m thinking it would make sense to offer two modes in Pagoda: one for SSR and another specifically for building APIs.

The idea is to use a container model to split into API and SSR mode and let users add their own modules. The SSR-only setup might become limiting as projects grow, so this approach gives people more options and room to evolve their stack as their needs change.

I might be wrong with the solution part, but please let me know what do you think about this problem?

**Comment by mikestefanello** [comment]
> I think Pagoda is perfect for small businesses or side projects, but once you start scaling up, you’ll need API endpoints that can work with the frontend. 

Can you elaborate on what _complicated interfaces_ meant that SSR wasn't an option anymore? I can understand if you're developing a heavy front-end application such as Figma, but I would imagine that SSR can take you extremely far and most likely cover most use-cases. Of course though, it comes down to preference and picking the tools that you prefer to work with. But I don't believe that SSR is only for small or hobby projects, from technical point of view. If you have a large engineering team, that can be a different story, especially if you have dedicated frontend developers who are skilled in some JS framework - but that has nothing to do with this project or any specific technology.

The entire basis and motivation of this project was to emphasize going in that direction compared to an API and some JS framework. I wanted to avoid JS at all costs which is even more to the point why I don't have an interest in supporting building out an API. This project was to prove that you don't need those, if you don't want to work with them (which I'm sure many Go devs prefer). I am personally way more of a fan of sticking to simplicity and Go and only if my requirements prove that that isn't sufficient would I want to explore other options. This was also the basis of switching from defaulting to Postgres to SQLite.

And even if I was interested in providing some API foundation, I would much prefer this project be very good at one thing, then decent at a bunch.

**Comment by GeraltO18** [comment]
> if you have dedicated frontend developers who are skilled in some JS framework - but that has nothing to do with this project or any specific technology.

Sure, I do understand that pagoda is focused for SSR. But I thought it would be nice to have another way too. 
>This project was to prove that you don't need those, if you don't want to work with them (which I'm sure many Go devs prefer).
Anyways, I think I got answer and it's to the point which I agree too😂. Thanks for taking time out to answer and explain.
>And even if I was interested in providing some API foundation, I would much prefer this project be very good at one thing, then decent at a bunch.
💯 Agreed on this. I was building a Saas, and it got little bigger, and I needed some complex client server communication and that's the part that made me think why do we not have an API on pagoda, I am sure someone just like me would have faced this. hence the issue. Anyways Thanks again.

Please let me know if you are planning on any new features for pagoda. I would be happy to work on :)

**Comment by mikestefanello** [comment]
Very cool to hear you're using this project as a starter for SaaS. If you ever can share any information/links about it, I would love to see it. I would also be interested to see what UIs were giving you trouble with a SSR approach. And out of curiosity, if you want to share, let me know what you decided to use for the API (sticking with Echo?) and frontend/JS.

I don't have anything planned for pagoda now, but I'm sure that will change once I get some more free time to dedicate to the project. Thanks for the offer!

**Comment by GeraltO18** [comment]
>If you ever can share any information/links about it, I would love to see it. I would also be interested to see what UIs were giving you trouble with a SSR approach.

Sure, I'm currently developing the UI in React. One of the features I'm working on is a flow-based service creation for users, which I also want to extend to mobile. I'm using a library called [React Flow](https://reactflow.dev/) for this purpose. Not sure if you're interested in the product idea, but it's a marketing tool that helps users build referral forms.

 >if you want to share, let me know what you decided to use for the API (sticking with Echo?) and frontend/JS.
 
 Yes, I am currently sticking to echo as it provides most of the things I need, out of box. For frontend, I am using React.
 
 I also have some experience with similar web servers like Temporal, and there's one feature I found particularly useful—it's called the workflow. I think having something like that in Pagoda would be great. It might not be a perfect fit, but it's an idea. You can check it out here: [Temporal Workflows](https://docs.temporal.io/workflows) and would love to hear your opinion on this. Thanks!

**Comment by mikestefanello** [comment]
Interesting. I can certainly see why SSR can be quite difficult for something like that.

I've worked with Cadence before (Temporal's predecessor). Both are amazing projects. I don't think a complete workflow orchestration system makes sense to be built in to a simple web app kit like Pagoda. If you need something with that kind of power, it's definitely best left as a standalone system that you can integrate with.

Good luck with your project!
