### ISSUE TITLE
How a task saving its data into DB by Ent?

### ISSUE THREAD

**Issue by akiranguyenvni** [mikestefanello/pagoda#8]
Hi Mikestefanello,

Your kit is awesome for starter like me.
I'm researching how to utilizing your kit to build an Web App.
My purpose is that:
- A task runs in background to fetch data from a website. Then save obtained data into Postgres db utilizing Ent
- When a client fetches router(GET), the data is load from Postgres db to show on HTML

My problem is:
- When saving data, like `/routes/*.go`, it needs 2 variables `c`(*Container) and `ctx`(echo.Context) to manipulate `c.Container.ORM`. But `ctx` of a task handler(in `/worker/tasks/*.go`) is `context.Context`(using reflect I see that: `*context.timerCtx`). Therefore I couldn't save data to db.
Could you tell me how to save data to db in worker?(If there is any sample code, really appreciate your help)

Thanks

**Comment by mikestefanello** [comment]
Hi,

Thanks! I'm glad to hear that it's useful for you.

In the routes, the _context_ you pass to the ORM methods isn't actually `echo.Context` but rather `context.Context` - it just may seem confusing because the param in the route and task handler are both named the same (`ctx`).

The route is something like this:
```
func (c *login) Post(ctx echo.Context) error {
	u, err := c.Container.ORM.User.
		Query().
		Where(email).
		Only(ctx.Request().Context())
}
```

Here, you're getting the actual context (`context.Context`) by doing `ctx.Request().Context()`. That's the context of the HTTP request.

In a task handler, you would just pass the `ctx` directly in:
```
func (p *ExampleProcessor) ProcessTask(ctx context.Context, t *asynq.Task) error {
	u, err := p.ORM.User.
		Query().
		Where(email).
		Only(ctx)
}
```

Now the only problem is that `p.ORM` doesn't exist, by default. You would have to initialize an ORM client and add it to `ExampleProcessor`. If you need help doing something like that, just let me know.

**Comment by akiranguyenvni** [comment]
Thank Mikestefanello for your explanation,
I finally can access db in worker. Your advice helped me a lot.

**Comment by mikestefanello** [comment]
You're welcome. Feel free to open another issue if you have any more questions.
