### ISSUE TITLE
Form Nesting?

### ISSUE THREAD

**Issue by aren55555** [mikestefanello/pagoda#85]
I've been trying to create a nested form type but haven't had any success. For example:

```go
type addressForm struct {
	Address1   string `form:"address1" validate:"required"`
	Address2   string `form:"address2" validate:"required"`
	City       string `form:"city" validate:"required"`
	State      string `form:"state" validate:"required"`
	PostalCode string `form:"postalCode" validate:"required"`
	Country    string `form:"country" validate:"required"`
}
type createOrderForm struct {
	FirstName string      `form:"firstName" validate:"required"`
	LastName  string      `form:"lastName" validate:"required"`
	Shipping  addressForm `form:"shipping" validate:"required"`
	Billing   addressForm `form:"billing" validate:"required"`
	form.Submission
}
```

When I render the HTML `<input>` in my template `.gohtml`, what should the value of the `name` property be? `shipping.name` or `shippingName` or otherwise? I've tried to figure it out myself but haven't had any success. Is this even supported, or should my form type be entirely flat?

Thank you!

**Comment by mikestefanello** [comment]
I'm not really sure since I've never tried that. This is really an [Echo](https://github.com/labstack/echo) question since that provides this functionality. I'd recommend searching through their documentation and issues. I'm sure someone else has ran in to this.

I came across [this](https://github.com/labstack/echo/issues/2070) after a quick search and it seems to suggest that the names need to be unique, but it's a couple of years old and that seems very limiting if it's true.
